<?php

namespace AppBundle\Repository;

/**
 * CartLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartLogRepository extends \Doctrine\ORM\EntityRepository
{
}
